create extension if not exists pgcrypto;

create table if not exists public.clientes (
    id bigint generated by default as identity primary key,
    nome text not null,
    bybit_key text,
    bybit_secret text,
    tg_token text,
    tg_api_key text,
    chat_id text,
    status text not null default 'ativo',
    saldo_base numeric(18, 8) not null default 1000.0,
    is_testnet boolean not null default true,
    balance_source text not null default 'form_test_balance',
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.trades (
    id bigint generated by default as identity primary key,
    client_id bigint references public.clientes(id) on delete cascade,
    pair text not null,
    side text not null,
    pnl_pct numeric(18, 8) default 0,
    profit numeric(18, 8) default 0,
    entry_price numeric(18, 8) default 0,
    closed_at text,
    notes text,
    status text not null default 'closed',
    nome_cliente text,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_clientes_status on public.clientes(status);
create index if not exists idx_trades_client_id on public.trades(client_id);
create index if not exists idx_trades_status on public.trades(status);
create index if not exists idx_trades_created_at on public.trades(created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists trg_clientes_updated_at on public.clientes;
create trigger trg_clientes_updated_at
before update on public.clientes
for each row
execute function public.set_updated_at();
