create extension if not exists pgcrypto;

create table if not exists public.clientes (
    id bigint generated by default as identity primary key,
    organization_id uuid,
    nome text not null,
    bybit_key text,
    bybit_secret text,
    tg_token text,
    tg_api_key text,
    chat_id text,
    status text not null default 'ativo',
    saldo_base numeric(18, 8) not null default 1000.0,
    is_testnet boolean not null default true,
    account_mode text not null default 'testnet',
    balance_source text not null default 'broker_testnet_balance',
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

alter table public.clientes add column if not exists tg_api_key text;
alter table public.clientes add column if not exists account_mode text;
alter table public.clientes add column if not exists balance_source text;
alter table public.clientes add column if not exists updated_at timestamptz not null default timezone('utc', now());

-- Multi-tenancy: add organization_id to existing tables created without the column
alter table public.clientes add column if not exists organization_id uuid default auth.uid();

update public.clientes
set account_mode = case
    when coalesce(is_testnet, true) then 'testnet'
    else 'real'
end
where account_mode is null or btrim(account_mode) = '';

update public.clientes
set balance_source = case
    when account_mode = 'testnet' then 'broker_testnet_balance'
    else 'broker_real_balance'
end
where balance_source is null
   or btrim(balance_source) = ''
   or balance_source = 'form_test_balance';

create table if not exists public.trades (
    id bigint generated by default as identity primary key,
    client_id bigint references public.clientes(id) on delete cascade,
    pair text not null,
    side text not null,
    pnl_pct numeric(18, 8) default 0,
    profit numeric(18, 8) default 0,
    entry_price numeric(18, 8) default 0,
    closed_at text,
    notes text,
    status text not null default 'closed',
    nome_cliente text,
    created_at timestamptz not null default timezone('utc', now())
);

alter table public.trades add column if not exists entry_price numeric(18, 8) default 0;
alter table public.trades add column if not exists nome_cliente text;

create index if not exists idx_clientes_status on public.clientes(status);
create index if not exists idx_trades_client_id on public.trades(client_id);
create index if not exists idx_trades_status on public.trades(status);
create index if not exists idx_trades_created_at on public.trades(created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists trg_clientes_updated_at on public.clientes;
create trigger trg_clientes_updated_at
before update on public.clientes
for each row
execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Multi-tenancy: enforce organization_id = auth.uid() on every INSERT
-- ---------------------------------------------------------------------------

-- Trigger function: overwrites organization_id with the JWT caller's uid so that
-- even if the application omits the field (or passes a wrong value) the row is
-- always owned by the authenticated user.
create or replace function public.set_organization_id()
returns trigger
language plpgsql
security invoker
as $$
begin
    -- Reject inserts that arrive without an authenticated JWT.
    if auth.uid() is null then
        raise exception 'organization_id cannot be set: no authenticated user (auth.uid() is NULL)';
    end if;
    new.organization_id = auth.uid();
    return new;
end;
$$;

drop trigger if exists trg_clientes_set_organization_id on public.clientes;
create trigger trg_clientes_set_organization_id
before insert on public.clientes
for each row
execute function public.set_organization_id();

-- ---------------------------------------------------------------------------
-- Row-Level Security (RLS)
-- ---------------------------------------------------------------------------

alter table public.clientes enable row level security;

-- Users may only see rows that belong to their organization.
drop policy if exists clientes_select_own_org on public.clientes;
create policy clientes_select_own_org
on public.clientes
for select
using (organization_id = auth.uid());

-- Users may only insert rows for their own organization.
drop policy if exists clientes_insert_own_org on public.clientes;
create policy clientes_insert_own_org
on public.clientes
for insert
with check (organization_id = auth.uid());

-- Users may only update rows that belong to their organization.
drop policy if exists clientes_update_own_org on public.clientes;
create policy clientes_update_own_org
on public.clientes
for update
using (organization_id = auth.uid())
with check (organization_id = auth.uid());

-- Users may only delete rows that belong to their organization.
drop policy if exists clientes_delete_own_org on public.clientes;
create policy clientes_delete_own_org
on public.clientes
for delete
using (organization_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Safe backfill for rows that pre-date multi-tenancy
-- ---------------------------------------------------------------------------
-- Run this ONCE after you know which auth.uid() (organization_id) should own
-- the existing records.  Replace the placeholder UUID with the real value.
--
-- To find the right UUID: look up the owner's auth.uid() in the
-- auth.users table:
--     SELECT id FROM auth.users WHERE email = 'owner@example.com';
--
-- Then execute:
--
--   UPDATE public.clientes
--   SET    organization_id = '<owner-auth-uid-here>'::uuid
--   WHERE  organization_id IS NULL;
--
-- After the backfill you may add a NOT NULL constraint if desired:
--
--   ALTER TABLE public.clientes
--   ALTER COLUMN organization_id SET NOT NULL;
-- ---------------------------------------------------------------------------
